# Final project - Ensemble Models

### Loading Data

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [6]:
# Loading data
df = pd.read_csv("../data/allwine-1.csv", index_col=0)

In [7]:
# Column Names
df.columns.to_list()

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [ ]:
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.743787,0.805266,-1.455948,-0.541531,-0.334525,-0.539436,-0.978159,0.146723,-0.755850,-1.297136,0
1,-0.520914,1.798500,-1.455948,-0.047918,0.129345,0.787432,-0.998211,-1.220838,-0.062351,-0.960761,0
2,-0.520914,1.136344,-1.251203,-0.259467,0.002835,-0.160331,-0.994200,-0.956148,-0.235726,-0.960761,0
3,1.373509,-1.512280,1.410480,-0.541531,-0.355610,0.029222,-0.974148,-1.397297,-0.640267,-0.960761,1
4,-0.743787,0.805266,-1.455948,-0.541531,-0.334525,-0.539436,-0.978159,0.146723,-0.755850,-1.297136,0
5,-0.743787,0.584547,-1.455948,-0.612047,-0.355610,-0.349884,-0.978159,0.146723,-0.755850,-1.297136,0
6,-0.465196,0.253469,-1.148831,-0.753079,-0.482120,-0.160331,-1.006232,-0.779689,-1.333765,-1.297136,0
7,-0.799505,0.529368,-1.455948,-1.035144,-0.566460,-0.160331,-1.042326,-0.382655,-1.275973,-0.792573,1
8,-0.520914,0.143110,-1.353576,-0.471015,-0.397780,-0.728989,-0.998211,-0.515000,-0.698058,-1.213043,1
9,-0.688069,-0.298327,0.386756,2.420145,-0.439950,0.029222,-0.978159,-0.559115,0.631147,-0.372104,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3198 entries, 0 to 3197
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fixed acidity        3198 non-null   float64
 1   volatile acidity     3198 non-null   float64
 2   citric acid          3198 non-null   float64
 3   residual sugar       3198 non-null   float64
 4   chlorides            3198 non-null   float64
 5   free sulfur dioxide  3198 non-null   float64
 6   density              3198 non-null   float64
 7   pH                   3198 non-null   float64
 8   sulphates            3198 non-null   float64
 9   alcohol              3198 non-null   float64
 10  quality              3198 non-null   int64
dtypes: float64(10), int64(1)
memory usage: 299.8 KB

In [10]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,density,pH,sulphates,alcohol,quality
count,3.198000e+03,3.198000e+03,3.198000e+03,3.198000e+03,3.198000e+03,3.198000e+03,3.198000e+03,3.198000e+03,3.198000e+03,3.198000e+03,3198.000000
mean,-3.732682e-16,-3.643809e-16,1.688594e-16,5.332403e-17,-1.777468e-16,-6.221137e-17,-1.848566e-15,2.132961e-16,-3.377189e-16,-3.554936e-17,0.534709
std,1.000156e+00,1.000156e+00,1.000156e+00,1.000156e+00,1.000156e+00,1.000156e+00,1.000156e+00,1.000156e+00,1.000156e+00,1.000156e+00,0.498872
min,-2.303900e+00,-2.395155e+00,-1.623825e+00,-1.246692e+00,-1.683967e+00,-1.487200e+00,-1.133162e+00,-3.250120e+00,-2.085055e+00,-2.138075e+00,0.000000
25%,-6.880688e-01,-7.413923e-01,-9.041204e-01,-4.710149e-01,-3.766953e-01,-7.930922e-01,-9.992135e-01,-7.796891e-01,-6.402666e-01,-7.137768e-01,0.000000
50%,-1.883037e-01,-3.776619e-02,-6.651164e-02,-2.594666e-01,-1.744349e-01,-2.140109e-01,-7.166201e-04,-2.683110e-03,-1.977143e-01,-1.262511e-01,1.000000
75%,5.638545e-01,6.221545e-01,7.962457e-01,6.705718e-02,8.597896e-02,5.481191e-01,9.990931e-01,7.564772e-01,4.338530e-01,6.383188e-01,1.000000
max,4.580738e+00,5.932391e+00,3.824068e+00,9.138676e+00,1.115258e+01,5.245422e+00,1.140202e+00,3.769595e+00,7.944553e+00,4.311531e+00,1.000000

# Task 1 - Build Simple Logistic Regression Model

In [11]:
# Split features and target variable
X = df.drop("quality", axis=1)
y = df["quality"]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Sigmoid function:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Log likelihood:
def log_likelihood(X, y, weights):
    linear_model = np.dot(X, weights)
    predicted = sigmoid(linear_model)
    likelihood = np.sum(y * np.log(predicted) + (1 - y) * np.log(1 - predicted))
    return likelihood

sigmoid(X)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,density,pH,sulphates,alcohol
0,0.322177,0.691100,0.189088,0.367832,0.417140,0.368319,0.273257,0.536615,0.319548,0.214647
1,0.372639,0.857966,0.189088,0.488023,0.532291,0.687280,0.269293,0.227789,0.484417,0.276726
2,0.372639,0.757008,0.222492,0.435495,0.500709,0.460003,0.270083,0.277650,0.441340,0.276726
3,0.797946,0.180601,0.803842,0.367832,0.412023,0.507305,0.274054,0.198245,0.345186,0.276726
4,0.322177,0.691100,0.189088,0.367832,0.417140,0.368319,0.273257,0.536615,0.319548,0.214647
...,...,...,...,...,...,...,...,...,...,...
3193,0.267072,0.648182,0.309800,0.399935,0.577365,0.837175,0.724645,0.811259,0.455605,0.660906
3194,0.250932,0.553776,0.307887,0.462865,0.354136,0.894584,0.723221,0.854369,0.682228,0.748945
3195,0.281931,0.574715,0.305497,0.491290,0.521387,0.778854,0.725271,0.761824,0.681915,0.721904
3196,0.236450,0.707895,0.338563,0.417964,0.471822,0.836156,0.724295,0.853003,0.637541,0.608149
3197,0.263247,0.259374,0.776403,0.697622,0.413036,0.538094,0.727212,0.722729,0.574816,0.699112

# Task 2 - Build 2-Layer Ensemble (Logistic Regression Tree)

# Task 3 - Build 3-Layer Deep Ensemble Model

# Task 4 - Generalize to N Layers